[tools]
node = "lts"
ripgrep = "latest"
starship = "latest"
bat = "latest"
eza = "latest"
fd = "latest"
zoxide = "latest"
sheldon = "latest"
dust = "latest"
duf = "latest"
yazi = "latest"
btop = "latest"
lazygit = "latest"
age = "latest"
sops = "latest"

[settings]
auto_install = true
experimental = true
